version: "3.4"

services:
  app_postgres:
    build:
      context: .
      dockerfile: cli/templates/Dockerfile
    image: mazzolino/crystal-sync
    entrypoint: sh
    command: -c "crystal-sync dump postgres://postgres:postgres@postgres1/postgres | crystal-sync load postgres://postgres:postgres@postgres2/postgres?schema=test"
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    networks:
      - backend
    depends_on:
      - postgres1
      - postgres2

  app_mysql:
    build:
      context: .
      dockerfile: cli/templates/Dockerfile
    image: mazzolino/crystal-sync
    entrypoint: sh
    command: -c "crystal-sync dump mysql://root:secret@mysql1/sync | crystal-sync load mysql://root:secret@mysql2/sync"
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    networks:
      - backend
    depends_on:
      - mysql1
      - mysql2

  postgres1:
    image: postgres:9.6
    networks:
      - backend

  postgres2:
    image: postgres:9.6
    networks:
      - backend

  mysql1:
    image: mysql:5
    environment:
      MYSQL_DATABASE: sync
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - backend

  mysql2:
    image: mysql:5
    command: --max-allowed-packet=16M
    environment:
      MYSQL_DATABASE: sync
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - backend

networks:
  backend:
