version: "3.4"

services:
  app:
    build: .
    environment:
      DATABASE_SOURCE_URL: postgres://postgres:postgres@db1/postgres
      DATABASE_TARGET_URL: postgres://postgres:postgres@db2/postgres
    volumes:
      - .:/usr/src/app
    networks:
      - backend
    depends_on:
      - db1
      - db2

  db1:
    image: postgres:9.6
    networks:
      - backend

  db2:
    image: postgres:9.6
    networks:
      - backend

networks:
  backend:
